# name of workflow
name: test workflow
# event that will trigger the workflow
on:
  pull_request: 
    types: [ opened,reopened ]

# jobs
jobs:
  merge:
    
     name: Auto merge
     runs-on: ubuntu-latest
     steps:
       - uses: hmarr/auto-approve-action@v2.0.0
         if: github.actor == 'zachy_dev' || github.actor == 'dependent-preview[bot]'
         with:
           github-token: "${{ secret.GITHUB_TOKEN}}" 
       - name: Finishing up and merging PR
         run: echo merged PR!!
