# name of workflow
name: test workflow
# event that will trigger the workflow
on:
  pull_request: 
    types: [ opened,reopened ]

# jobs
jobs:
  merge:
    
     name: Approve and Auto merge
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
       - uses: hmarr/auto-approve-action@v2.0.0
         if: github.actor == 'zachydev' || github.actor == 'dependent-preview[bot]'
         with:
           github-token: "${{ secrets.GITHUB_TOKEN}}" 
       - name: Finishing up and approving PR
         run: echo approved pr
         

